import React from 'react'
import { useRouter } from 'next/router';
import Head from 'next/head'

import { styled } from '@mui/system';

import DownloadSharpIcon from '@mui/icons-material/DownloadSharp';
import LaunchSharpIcon from '@mui/icons-material/LaunchSharp';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';

import Header from '../components/organisms/header/Header'
import styles from '../styles/detail.module.css'
import DetailPageFavoriteIcon from '../components/atoms/icons/DetailPageFavoriteIcon';


// DownloadSharpIconのcss
const MyDownloadSharpIcon = styled(DownloadSharpIcon)({
  cursor: "pointer",
  fontSize: "30px",
  borderRadius: "18px",
  color: "rgba(255, 255, 255, 0.8)",
  zIndex:"10",
  "&:hover": {
    color:"rgb(255, 255, 255)",
  }
})
// LaunchSharpIconのcss
const MyLaunchSharpIcon = styled(LaunchSharpIcon)({
  cursor: "pointer",
  fontSize: "16px",
  color:"black",
  "&:hover": {
    color:"rgb(80, 80, 80)",
  }
})
// ArrowBackIconのcss
const MyArrowBackIcon = styled(ArrowBackIcon)({
  cursor: "pointer",
  color: "rgb(255, 255, 255, 0.8)",
  fontSize: "30px",
})

const detail = () => {
  const router = useRouter();
  if(!router.query.datetaken)return;
  return (
    <>
      <Head>
        <title>詳細ページ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/VPhotoIcon2.ico" />
      </Head>
      <Header />
      <div className={styles.content_area}>
        <div className={styles.back_icon}>
          <MyArrowBackIcon onClick={() => router.back()}/>
        </div>
        <div className={styles.photo_area}>
          <img className={styles.photo} src={router.query.url_l} alt='#' />
        </div>
        <div className={styles.icon_area}>
          <div className={styles.photo_like_icon}>
            <DetailPageFavoriteIcon 
              id={router.query.id}
              title={router.query.title}
              url_m={router.query.url_m}
              url_l={router.query.url_l}
              ownername={router.query.ownername}
              datetaken={router.query.datetaken}
              tags={router.query.tags}
            />
          </div>
          <div className={styles.photo_download_icon}>
            <a 
              className={styles.flickr_detailpage_link_a_tag} 
              target="_blank" 
              rel="noopener noreferrer" 
              href={`https://www.flickr.com/photos/valorantesports/${router.query.id}/sizes/l/`}
            >
              <MyDownloadSharpIcon />
            </a>
          </div>
        </div>
      </div>
      <div className={styles.description_area}>
        <div className={styles.shooting_date_area}>
          <p className={styles.shooting_date_index}>撮影日</p>
          <p className={styles.shooting_date}>{router.query.datetaken.slice(0, 10)}</p>
        </div>
        <div className={styles.title_area}>
          <p className={styles.title_index}>タイトル</p>
          <p className={styles.title}>{router.query.title}</p>
        </div>
        <div className={styles.poster_area}>
          <p className={styles.poster_name_index}>投稿者</p>
          <p className={styles.poster_name}>{router.query.ownername}</p>
        </div>
        <div className={styles.flickr_detailpage_link_area}>
          <p className={styles.flickr_detailpage_link_index}>掲載元</p>
          <p className={styles.flickr_detailpage_link}>
            <a className={styles.flickr_detailpage_link_a_tag} target="_blank" rel="noopener noreferrer" href={`https://www.flickr.com/photos/valorantesports/${router.query.id}/in/album-${router.query.secret}/`}>
              flickr.com
              <MyLaunchSharpIcon />
            </a>
          </p>
        </div>
      </div>
    </>
  )
}

export default detail;