import React from 'react'
import Head from 'next/head'

import { styled } from '@mui/system';
import FavoriteBorderIcon from '@mui/icons-material/FavoriteBorder';
import { Select, FormControl, MenuItem } from '@mui/material';

import styles from '../styles/Home.module.css'
import FavoriteHeader from '../components/FavoriteHeader';
import PhotoList from '../components/PhotoList';
import FavoritePhotoList from '../components/FavoritePhotoList';

// FavoriteBorderIconのcss
const MyFavoriteBorderIcon = styled(FavoriteBorderIcon)({
  cursor: "pointer",
  padding: "7px",
  fontSize: "42px",
  borderRadius: "18px",
  position: "absolute",
  bottom: "20px",
  right: "20px",
  color:"white",
  zIndex:"10",
  "&:hover": {
    color:"red",
  }
})
const MyTeamSelect = styled(Select)({
  width: "200px",
  height: "40px",
  borderRadius: "40px",
})
const MyDaySelect = styled(Select)({
  width: "150px",
  height: "40px",
  borderRadius: "40px",
})
const MytournamentSelect = styled(Select)({
  width: "350px",
  height: "40px",
  borderRadius: "40px",
})

const favorite = () => {

  return (
    <>
      <Head>
        <title>V-Photo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/VPhotoIcon2.ico" />
      </Head>
      <FavoriteHeader />
      <div className={styles.sort_area}>
        <div className={styles.select_box}>
        <FormControl>
            <MyTeamSelect 
              defaultValue={'すべてのチーム'}
              id="team-select"
            >
              <MenuItem value={'すべてのチーム'}>すべてのチーム</MenuItem>
              <MenuItem value={'ZETA DIVISION'}>ZETA DIVISION</MenuItem>
              <MenuItem value={'Crazy Raccoon'}>Crazy Raccoon</MenuItem>
              <MenuItem value={'Northeption'}>Northeption</MenuItem>
            </MyTeamSelect>
          </FormControl>
        </div>
        <div className={styles.select_box}>
          <FormControl>
            <MyDaySelect defaultValue={'すべての日程'} id="day-select">
              <MenuItem value={'すべての日程'}>すべての日程</MenuItem>
              <MenuItem value={'DAY1'}>DAY1</MenuItem>
              <MenuItem value={'DAY2'}>DAY2</MenuItem>
              <MenuItem value={'DAY3'}>DAY3</MenuItem>
            </MyDaySelect>
          </FormControl>

        </div>
        <div className={styles.select_box}>
          <FormControl>
            <MytournamentSelect defaultValue={'すべての大会'} id="tournament-select">
              <MenuItem value={'すべての大会'}>すべての大会</MenuItem>
              <MenuItem value={'vct2021: Stage 2 Masters - Reykjavík'}>vct2021: Stage 2 Masters - Reykjavík</MenuItem>
              <MenuItem value={'vct2021: Stage 3 Masters - Berlin'}>vct2021: Stage 3 Masters - Berlin</MenuItem>
              <MenuItem value={'VALORANT Champions 2021'}>VALORANT Champions 2021</MenuItem>
              <MenuItem value={'vct2022: Stage 1 Masters - Reykjavík'}>vct2022: Stage 1 Masters - Reykjavík</MenuItem>
              <MenuItem value={'vct2022: Stage 2 Masters - Copenhagen'}>vct2022: Stage 2 Masters - Copenhagen</MenuItem>
              <MenuItem value={'VALORANT Champions 2022'}>VALORANT Champions 2022</MenuItem>
            </MytournamentSelect>

          </FormControl>
        </div>
      </div>
      <div className={styles.container}>
        <FavoritePhotoList />
      </div>
    </>
  )
}

export default favorite