import React from 'react'
import Head from 'next/head'

import FavoriteHeader from '../components/organisms/header/FavoriteHeader';
import FavoritePhotoList from '../components/organisms/photolist/FavoritePhotoList';
import styles from '../styles/Home.module.css'

const Favorite = () => {
  return (
    <>
      <Head>
        <title>V-Photo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/VPhotoIcon2.ico" />
      </Head>
      <FavoriteHeader />
      <div className={styles.container}>
        <FavoritePhotoList />
      </div>
    </>
  )
}

export default Favorite;