import React from 'react'
import Link from 'next/link'
import { Button,TextField, FormLabel, Divider } from '@mui/material';
import { styled } from '@mui/system';

import styles from '../styles/login.module.css'
import FormHeader from '../components/FormHeader'
import Head from 'next/head'

const MyFormLabel = styled(FormLabel)({
  display:"block",
  fontWeight:"bold",
  paddingBottom:"4px",
})
const MyTextField = styled(TextField)({
  borderRadius:"30px",
  width:"100%",
})
const MyButton = styled(Button)({
  marginBottom:"10px",
  // borderColor:"RGB(237, 242, 247)",
  color:"black",
  fontWeight:"bold",
  backgroundColor:"RGB(210, 210, 210)",
  "&:hover": {
    backgroundColor:"RGB(62, 140, 236)",
    color:"white",
  }
})
const MyDivider = styled(Divider)({
  marginBottom:"10px",
})


const login = () => {
  return (
    <>
      <Head>
        <title>ログイン</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/VPhotoIcon2.ico" />
      </Head>
      <FormHeader />
      <div className={styles.login}>
        <div className={styles.title_text_area}>
          <text className={styles.title_text}>
            ログイン
          </text>
        </div>
        <form>
          <div className={styles.email_area}>
            <MyFormLabel>Email address</MyFormLabel>
            <MyTextField placeholder='Email address' variant="outlined" size='small' />
          </div>
          <div className={styles.password_area}>
            <MyFormLabel>Password</MyFormLabel>
            <MyTextField placeholder="Password" variant="outlined" size='small'/>
          </div>
 
          <MyButton variant="contained" fullWidth={true} >
            ログイン
          </MyButton>

        </form>
        <div  className={styles.signup_link_area}>
          ユーザー登録は
            <Link href={"/signup1"} style={{textDecoration:"none"}}>
              <span className={styles.signup_link}>
                こちら
              </span>
            </Link>
          から
        </div>
        <MyDivider>または</MyDivider>
        <MyButton variant="contained" fullWidth={true}>
          Googleでログイン
        </MyButton>

      </div>
    </>
  )
}

export default login