import React from 'react'
import Link from 'next/link'

import { Box, Button, Center, FormLabel, Input, Text, Grid, GridItem } from '@chakra-ui/react'
import styles from '../styles/login.module.css'
import FormHeader from '../components/FormHeader'
import Head from 'next/head'


const login = () => {
  return (
    <>
      <Head>
        <title>ログイン</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/VPhotoIcon2.ico" />
      </Head>
      <FormHeader />
      <div className={styles.login}>
        <Text 
          pb="20px" 
          fontSize='2xl' 
          fontWeight="700"
        >
          ログイン
        </Text>
        <form>
          {/* {error && <p style={{color: 'red'}}>{error}</p>} */}
          <Box>
            <FormLabel>Email address</FormLabel>
            <Input 
                id="email"
                name="email"
                type="email"
                placeholder="email"
              />
          </Box>
          <Box mt="10px">
            <FormLabel>password</FormLabel>
            <Input 
                id="password"
                name="password"
                type="password"
                placeholder="password"
              />
          </Box>
          <Button 
            type='submit' 
            _hover={{backgroundColor:"rgba(206, 255, 0, 0.5)"}}
            mt="20px"
            w="100%"
          >
            ログイン
          </Button>
        </form>
        <Center mt="10px">
            ユーザー登録は
              <span className={styles.signup_link}>
                <Link href={"/signup"}>
                  こちら
                </Link>
              </span>
            から
        </Center>
        <Grid 
          templateColumns='repeat(3, 1fr)' 
          gap={1} 
          placeItems="center" 
          m="20px 0 10px 0"
        >
          <GridItem 
            colSpan={1} 
            w='100%' 
            h='1px' 
            bg='rgb(220, 220, 220)' 
          />
          <Center>または</Center>
          <GridItem 
            colStart={3} 
            w='100%' 
            h='1px' 
            bg='rgb(220, 220, 220)' 
          />
        </Grid>
        <Button 
          type='submit' 
          _hover={{backgroundColor:"rgba(206, 255, 0, 0.5)"}}
          w="100%"
        >
          Googleでログイン
        </Button>
      </div>
    </>
  )
}

export default login