import Head from 'next/head'
import React from 'react'

import PersonIcon from '@mui/icons-material/Person';
import { styled } from '@mui/system';

import Header from '../components/Header'
import styles from '../styles/mypage.module.css'
import { Button } from '@mui/material';


// PersonIconのcss
const MyPersonIcon = styled(PersonIcon)({
  cursor: "pointer",
  color:"white",
  fontSize:"120px",
  border:"solid 1px black",
  backgroundColor:"black",
  borderRadius: "120px",
  margin:"15px 5px 5px 5px",
})

const MyButton = styled(Button)({
  marginBottom:"10px",
  borderRadius: "50px",
  // borderColor:"RGB(237, 242, 247)",
  color:"black",
  fontWeight:"bold",
  backgroundColor:"RGB(210, 210, 210)",
  "&:hover": {
    backgroundColor:"RGB(62, 140, 236)",
    color:"white",
  }
})

const mypage = () => {
  return (
    <>
      <Head>
        <title>Myページ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/VPhotoIcon2.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <section>
          <div className={styles.user_profile}>
            <div className={styles.user_icon}>
              <MyPersonIcon />
            </div>
            <div className={styles.user_info}>
              <div className={styles.user_name}>taso</div>
              <div className={styles.user_birthdate}>1996/3/22</div>
              <div className={styles.user_memo}>ZETA DIVISIONのファンです。ZETA以外のチームも応援しています。JPリージョンの配信試合は基本的に全部見ています。海外チームだと、DRX、PRX、FNCが好きです。</div>
            </div>
          </div>
          <div className={styles.edit_area}>
            <div className={styles.edit_profile_button}>
              <MyButton>プロフィールを編集</MyButton>
            </div>
            <div className={styles.edit_pickup_button}>
              <MyButton>ピックアップを編集</MyButton>
            </div>
          </div>
        </section>
        <section className={styles.pickup_section}>
          <h1 className={styles.pickup_title}>
            ピックアップ
          </h1>
          <div className={styles.pickup_area}>
            <img className={styles.pickup_photo} src="https://live.staticflickr.com/65535/52003190498_9e6fb8be4e_b.jpg" alt="#"/>
            <p className={styles.pickup_memo}>ZETAが日本初のプレーオフ進出を決めた際の写真です。</p>
          </div>
        </section>
      </main>
    </>
  )
}

export default mypage