// import React, { useState } from 'react'
// import Link from 'next/link'
// import Head from 'next/head'
// import { useRecoilValue } from 'recoil';
// import { Dayjs } from 'dayjs';
// import { doc, setDoc } from 'firebase/firestore'

// import { styled } from '@mui/system';
// import { Button,TextField, FormLabel, Divider } from '@mui/material';
// import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
// import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
// import Stack from '@mui/material/Stack';
// import { DesktopDatePicker } from '@mui/x-date-pickers/DesktopDatePicker';

// import styles from '../styles/signup.module.css'
// import FormHeader from '../components/FormHeader'
// import { profileState } from '../state/profileState';
// import { auth, db } from '../firestore/firebase';



// const MyFormLabel = styled(FormLabel)({
//   display:"block",
//   fontWeight:"bold",
//   paddingBottom:"4px",
// })
// const MyTextField = styled(TextField)({
//   borderRadius:"30px",
//   width:"100%",
// })
// const MyButton = styled(Button)({
//   marginBottom:"10px",
//   color:"black",
//   fontWeight:"bold",
//   backgroundColor:"RGB(210, 210, 210)",
//   "&:hover": {
//     backgroundColor:"RGB(62, 140, 236)",
//     color:"white",
//   }
// })
// const MyDivider = styled(Divider)({
//   marginBottom:"10px",
// })



// const signup_profile = () => {
//   const [value, setValue] = useState();
//   // const [value, setValue] = useState<Dayjs | null>();
//   const handleChange = (newValue) => {
//     // const handleChange = (newValue: Dayjs | null) => {
//     setValue(newValue);
//   };

// // プロフィール情報をuseRecoilValueで取得
// const profile = useRecoilValue(profileState);

// // ユーザーネームをuseStateで管理(初期値は編集前のもの)
// const [name, setName] = useState(profile.userName);

// // 変更(送信)ボタンを押したときにはしる関数
// const sendProfile = async(e:any) => {
// if(auth.currentUser === null){
//   return
// } 
// // 送信ボタンを押したときに、画面がリロードしないようにpreventDefaultが必要
// e.preventDefault();

// // console.log("userName:",name," userBirthday:",value.$d)
// // ブラウザ上で記入したprofileをfirebaseに送信
// const docRef = doc(db, "users", auth.currentUser.uid)
// const profile = {
//   userName:name,
//   userBirthday:value.$d,
// }
// await setDoc(docRef, profile);
// await router.push("/")
// }
//   return (
//     <>
//       <Head>
//         <title>ユーザー登録(2/2)</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/VPhotoIcon2.ico" />
//       </Head>
//       <FormHeader />
//       <div className={styles.signup}>
//         <div className={styles.title_area}>
//           <text className={styles.title}>
//             ユーザー登録&nbsp;
//           </text>
//           <text className={styles.sub_title}>
//             (2/2)
//           </text>
//         </div>
//           <form>
//           <div className={styles.user_name_area}>
//             <MyFormLabel>ユーザー名</MyFormLabel>
//             <MyTextField 
//               placeholder='ユーザー名' 
//               variant="outlined" 
//               onChange={(e) => setName(e.target.value)}  
//               size='small' 
//             />
//           </div>
//           <div className={styles.date_of_birth_area}>
//             <MyFormLabel>生年月日</MyFormLabel>
//             <LocalizationProvider dateAdapter={AdapterDayjs} >
//               <DesktopDatePicker
//                 inputFormat="YYYY/MM/DD"
//                 value={value}
//                 onChange={handleChange}
//                 renderInput={(params) => <TextField size="small" {...params} />}
//                 className={styles.date_select}
//               />
//             </LocalizationProvider>
//           </div>
//           <div>
//           <MyButton variant="contained" fullWidth={true} onClick={sendProfile}>
//             登録
//           </MyButton>
//           </div>
//         </form>
        
//       </div>
//     </>
//   )
// }

// export default signup_profile