import React from 'react'
import Link from 'next/link'

import {  FormLabel, Input, Button, Text, Box, Center } from '@chakra-ui/react'

import styles from '../styles/signup.module.css'
import Head from 'next/head'
import Header from '../components/Header'
import FormHeader from '../components/FormHeader'


const signup1 = () => {
  return (
    <>
      <Head>
        <title>ユーザー登録(1/2)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/VPhotoIcon2.ico" />
      </Head>
      <FormHeader />
      <div className={styles.signup}>
        <div className={styles.title_area}>
          <text className={styles.title}>
            ユーザー登録&nbsp;
          </text>
          <text className={styles.sub_title}>
            (1/2)
          </text>
        </div>
          <form>
          <Box>
            <FormLabel>Email address</FormLabel>
            <Input 
              name="email"
              type="email"
              placeholder="email"
            />
          </Box>
          <Box mt="10px">
            <FormLabel>password</FormLabel>
            <Input 
              name="password"
              type="password"
              placeholder="password"
            />
          </Box>
          <Box>
          <Button 
            type='submit' 
            _hover={{backgroundColor:"rgba(206, 255, 0, 0.5)"}}
            mt="30px"
            w="100%"
          >
            次へ
          </Button>
          </Box>
        </form>
        <Center mt="10px">
          登録済みの方は
            <span className={styles.login_link}>
              <Link href={"/login"}>
                こちら
              </Link>
            </span>
        </Center>
      </div>
    </>
  )
}

export default signup1