import React, { useState, useEffect }  from 'react'
import Link from 'next/link'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { createUserWithEmailAndPassword, getAuth } from 'firebase/auth'

import { styled } from '@mui/system';
import { TextField, FormLabel } from '@mui/material';

import styles from '../styles/signup.module.css'
import { firebaseApp } from '../firestore/firebase'
import FormHeader from '../components/organisms/header/FormHeader'
import { MyMuiSquareButton } from '../components/atoms/buttons/MyMuiSquareButton'


const MyFormLabel = styled(FormLabel)({
  display:"block",
  fontWeight:"bold",
  paddingBottom:"4px",
})

const Signup = () => {
  const auth = getAuth(firebaseApp);
  const router = useRouter();

  const [email, setEmail] = useState("")
  const [password, setPassword] = useState("")

  useEffect(() => {
    if(auth.currentUser){
      console.log("auth.currentUser",auth.currentUser)
      router.push("/")
    } else {
      console.log("auth.currentUser",auth.currentUser)
      return
    }
  },[]);

  const handleEmailChange = (e: React.ChangeEvent<HTMLTextAreaElement | HTMLInputElement>) => {
    setEmail(e.target.value)
  }
  const handlePasswordChange = (e: React.ChangeEvent<HTMLTextAreaElement | HTMLInputElement>) => {
    setPassword(e.target.value)
  }
  // emailとpasswordを登録する関数
  const signupWithEmail = (event: any) => {
    event.preventDefault();
    createUserWithEmailAndPassword(auth, email, password)
    .then(() => {
      router.push("/")
    })
    .catch((error) => {
      alert(error.message)
    }); 
  };

  return (
    <>
      <Head>
        <title>ユーザー登録</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/VPhotoIcon2.ico" />
      </Head>
      <FormHeader />
      <div className={styles.signup}>
        <div className={styles.title_area}>
          <text className={styles.title}>
            ユーザー登録&nbsp;
          </text>
        </div>
        <form>
        <div className={styles.email_area}>
          <MyFormLabel>Email address</MyFormLabel>
          <TextField
            placeholder='Email address' 
            variant="outlined" 
            size='small' 
            fullWidth={true}
            onChange={(e)=> handleEmailChange(e)}
          />
        </div>
        <div className={styles.password_area}>
          <MyFormLabel>Password</MyFormLabel>
          <TextField 
            placeholder="Password" 
            variant="outlined" 
            size='small' 
            fullWidth={true}
            onChange={(e) => handlePasswordChange(e)}
          />
        </div>
        <MyMuiSquareButton variant="contained" fullWidth={true} onClick={signupWithEmail}>
          登録
        </MyMuiSquareButton>
      </form>
        <div className={styles.signup_link_area}>
          登録済みの方は
            <Link href={"/login"} style={{textDecoration:"none"}}>
              <span className={styles.login_link}>
                こちら
              </span>
            </Link>
        </div>
      </div>
    </>
  )
}

export default Signup;